CREATE TABLE manos (
    entrada INTEGER,
    carta1 INTEGER not null,
    carta2 INTEGER not null,
    carta3 INTEGER not null,
    carta4 INTEGER not null,
    carta5 INTEGER not null,
    carta6 INTEGER not null,
    carta7 INTEGER not null,
    carta8 INTEGER not null,
    carta9 INTEGER not null,
    carta10 INTEGER not null,
    carta11 INTEGER not null,
    carta12 INTEGER not null,
    carta13 INTEGER not null,
    carta14 INTEGER not null,
    carta15 INTEGER not null,
    carta16 INTEGER not null,
    carta17 INTEGER not null,
    carta18 INTEGER not null,
    carta19 INTEGER not null,
    carta20 INTEGER not null,
    carta21 INTEGER not null,
    carta22 INTEGER not null,
    carta23 INTEGER not null,
    carta24 INTEGER not null,
    carta25 INTEGER not null,
    carta26 INTEGER not null,
    carta27 INTEGER not null,
    carta28 INTEGER not null,
    carta29 INTEGER not null,
    carta30 INTEGER not null,
    carta31 INTEGER not null,
    carta32 INTEGER not null,
    carta33 INTEGER not null,
    carta34 INTEGER not null,
    carta35 INTEGER not null,
    carta36 INTEGER not null,
    carta37 INTEGER not null,
    carta38 INTEGER not null,
    carta39 INTEGER not null,
    carta40 INTEGER not null,
    carta41 INTEGER not null,
    carta42 INTEGER not null,
    carta43 INTEGER not null,
    carta44 INTEGER not null,
    carta45 INTEGER not null,
    carta46 INTEGER not null,
    carta47 INTEGER not null,
    carta48 INTEGER not null,
    carta49 INTEGER not null,
    carta50 INTEGER not null,
    carta51 INTEGER not null,
    carta52 INTEGER not null,
    usuario VARCHAR(50),
    PRIMARY KEY(entrada),
    FOREIGN KEY(usuario) REFERENCES usuarios(usuario)
);

create table usuarios
(
    usuario varchar(50) not null unique,
    contra varchar(50) not null,
    correo varchar(100) not null unique,
    ip varchar(50) not null,
    verificado boolean not null,
    primary key (usuario)
);

create index manos_idx1 on manos (carta1, carta2, carta3, carta4, carta5, carta6, carta7, carta8, carta9, carta10, carta11, carta12, carta13, carta14, carta15, carta16, carta17, carta18, carta19, carta20, carta21, carta22, carta23, carta24, carta25, carta26);

create index manos_idx2 on manos (carta27, carta28, carta29, carta30, carta31, carta32, carta33, carta34, carta35, carta36, carta37, carta38, carta39, carta40, carta41, carta42, carta43, carta44, carta45, carta46, carta47, carta48, carta49, carta50, carta51, carta52);
